In [1]:
import numpy as np

In [2]:
english_score = np.array([55,89,76,65,48,70])
math_score = np.array([60,85,60,68,np.nan,60])
chinese_score = np.array([65,90,82,72,66,77])
mean = np.nanmean
npmax = np.nanmax
npmin = np.nanmin
std = np.nanstd

In [3]:
#1. 請計算各科成績平均、最大值、最小值、標準差，其中數學缺一筆資料可忽略?
np.hstack((mean(english_score), npmax(english_score),npmin(english_score),std(english_score)))
np.hstack((mean(math_score), npmax(math_score),npmin(math_score),std(math_score)))
np.hstack((mean(chinese_score), npmax(chinese_score),npmin(chinese_score), std(chinese_score)))


array([75.33333333, 90.        , 65.        ,  8.8254682 ])

In [4]:
#2. 第五位同學補考數學後成績為55，請計算補考後數學成績平均、最大值、最小值、標準差?
math_score[5 - 1] = 55
np.hstack((mean(english_score), npmax(english_score),npmin(english_score),std(english_score)))
np.hstack((mean(math_score), npmax(math_score),npmin(math_score),std(math_score)))
np.hstack((mean(chinese_score), npmax(chinese_score),npmin(chinese_score), std(chinese_score)))

array([75.33333333, 90.        , 65.        ,  8.8254682 ])

In [5]:
#3. 用補考後資料找出與國文成績相關係數最高的學科?
np.maximum(np.corrcoef(chinese_score, english_score, rowvar = True), np.corrcoef(chinese_score, math_score, rowvar = True))

array([[1.        , 0.97792828],
       [0.97792828, 1.        ]])