In [1]:
import numpy as np
import sys
sNum = 0
eNum = 20
multi = 3

In [2]:
#1.生成一個等差數列，首數為0，尾數為20，公差為1的數列。
answer1 = np.arange(sNum, eNum - sNum + 1) #整數等差1
answer1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [3]:
#2.呈上題，將以上數列取出偶數。
answer2 = answer1[sNum:eNum - sNum + 1:2]
answer2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [4]:
#3.呈1題，將數列取出3的倍數。
answer3 = answer1[multi:eNum - sNum + 1:multi]
answer3

array([ 3,  6,  9, 12, 15, 18])

In [5]:
# 4. [簡答題] 請問下列兩種將 Array 轉換成 List 的方式有何不同？
print('list(a): ', list(answer2))
print('tolist(): ', answer2.tolist())

print("list() 資料格式為", type(list(answer2)[1]) , "資料 整数（-9223372036854775808至9223372036854775807）")
print("tolist(): 資料格式為", type(answer2.tolist()[1]) , 'Python 3 int没有最大值')
# 資料格式不同 第一種list 轉為numpy格式的資料, tolist 是轉成python int

list(a):  [0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20]
tolist():  [0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20]
list() 資料格式為 <class 'numpy.int64'> 資料 整数（-9223372036854775808至9223372036854775807）
tolist(): 資料格式為 <class 'int'> Python 3 int没有最大值


In [30]:
# 5.請試著在程式中印出以下三個 NdArray 的屬性？（屬性：ndim、shape、size、dtype、itemsize、length、type）
def printAttrs(a):
    print('ndim = ', a.ndim)
    print('shape = ', a.shape)
    print('size = ', a.size)
    print('dtype = ', a.dtype)
    print('itemsize = ', a.itemsize)
    print('type = ', type(a[0]))
a = np.random.randint(10, size=6) 
b = np.random.randint(10, size=(3,4)) 
c = np.random.randint(10, size=(2,3,2)) 
printAttrs(a)
printAttrs(b)
printAttrs(c)

ndim =  1
shape =  (6,)
size =  6
dtype =  int64
itemsize =  8
type =  <class 'numpy.int64'>
ndim =  2
shape =  (3, 4)
size =  12
dtype =  int64
itemsize =  8
type =  <class 'numpy.ndarray'>
ndim =  3
shape =  (2, 3, 2)
size =  12
dtype =  int64
itemsize =  8
type =  <class 'numpy.ndarray'>


In [32]:
# 6.如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。
results = list(map(int, a))
type(results[1])

int